repos:
-   repo: local
    hooks:
    -   id: ruff-check
        name: Ruff Lint
        entry: uv run ruff check --fix
        language: system
        types: [python]

    -   id: ruff-format
        name: Ruff Format
        entry: uv run ruff format --check
        language: system
        types: [python]

    -   id: black
        name: Black
        entry: uv run black --check
        language: system
        types: [python]

    -   id: mypy
        name: Mypy
        entry: uv run mypy
        language: system
        types: [python]
        pass_filenames: false